[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 800
evm_version = "paris"
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
