[profile.default]
auto_detect_solc = false
solc = "0.8.28"
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@solady/=lib/solady/src",
  "forge-std/=lib/forge-std/src/"
]

bytecode_hash = 'none'
cbor_metadata = false

optimizer = true
optimizer_runs = 99_999_999
via_ir = true

evm_version = "prague"
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}"}
base_sepolia = { key = "${BASESCAN_API_KEY}"}
anvil = { key = "" }

[profile.via_ir]
via_ir = true
test = 'src'
out = 'via_ir-out'
